version: '3.8'

services:
  cv-analyzer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cvuser:cvpassword@postgres:5432/cvanalyzer
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cvanalyzer
      - POSTGRES_USER=cvuser
      - POSTGRES_PASSWORD=cvpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - cv-analyzer
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: